### ISSUE TITLE
as this works directly in comfy as picture you introduced ?

### ISSUE THREAD

**Issue by youforgetsomething** [taabata/SANA_LOWVRAM#1]
asking if there any other required vae ? or it just will work and not downloading any other than sana model .pth ?

**Comment by taabata** [comment]
You need to download the diffusers model which is a whole folder (includes vae, text encoder, transformer, scheduler, tokenizer).
https://huggingface.co/Efficient-Large-Model/Sana_600M_512px_diffusers/tree/main.

I have updated the code for automatic download of model, just choose the model from the model_path dropdown of the nodes. ("Efficient-Large-Model/Sana_600M_512px_diffusers" for example)

**Comment by youforgetsomething** [comment]
i don't want any "auto download" , where to put https://huggingface.co/Efficient-Large-Model/Sana_1600M_1024px_diffusers/tree/main that directory as whole one should placed where inside comfy ?

**Comment by taabata** [comment]
In ComfyUI/models/diffusers  create a new directory and place all folders and the model_index.json file inside that new directory.

**Comment by mycodeongit** [comment]
I placed the whole diffusers folder (includes vae, text encoder, transformer, scheduler, tokenizer) from the following link
https://huggingface.co/Efficient-Large-Model/Sana_600M_512px_diffusers/tree/main

Still getting the following error
<
SANATextEncode
[WinError 2] The system cannot find the file specified
>

Also, the automatic download feature is not working...

Any tips would be appreciated 

![pic](https://github.com/user-attachments/assets/98e40572-7bc5-4154-9a84-44fc803582ca)
![2025-01-07-20-32-02](https://github.com/user-attachments/assets/d689bd0d-c16f-4686-816e-c44c1b5e50c1)

**Comment by youforgetsomething** [comment]
what about gemma !? isn't this require gemma 2.2 ? where to place them if yes ?!
